/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        home: [];
        blog: [];
        about: [];
        contact: [];
        author: [
            {
                name: "user";
                required: true;
                binding: "username";
            }
        ];
        category: [
            {
                name: "category";
                required: true;
                binding: "slug";
            }
        ];
        post: [
            {
                name: "article";
                required: true;
                binding: "slug";
            }
        ];
        "dashboard.index": [];
        "dashboard.inbox": [];
        "dashboard.customers": [];
        "dashboard.settings": [];
        "dashboard.settings.members": [];
        "dashboard.settings.notifications": [];
        "dashboard.settings.security": [];
        "storage.local": [
            {
                name: "path";
                required: true;
            }
        ];
    }
}
export {};
